// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfNY7AXiZ0SJwi7aRYS8Jxg6lNb9ToAMU',
    appId: '1:261400152264:web:21c558654deba127e5fdfd',
    messagingSenderId: '261400152264',
    projectId: 'sistem-monitoring-mobil',
    authDomain: 'sistem-monitoring-mobil.firebaseapp.com',
    storageBucket: 'sistem-monitoring-mobil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdHITm3S01VHrk-67wA_g69fa1G05IUSA',
    appId: '1:261400152264:android:3faf84df85938019e5fdfd',
    messagingSenderId: '261400152264',
    projectId: 'sistem-monitoring-mobil',
    storageBucket: 'sistem-monitoring-mobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsCWN5MTjrJ6OO3MEv9AALMTpNDltNAk',
    appId: '1:261400152264:ios:1faf74db5d256804e5fdfd',
    messagingSenderId: '261400152264',
    projectId: 'sistem-monitoring-mobil',
    storageBucket: 'sistem-monitoring-mobil.firebasestorage.app',
    iosBundleId: 'com.example.sistemMonitoringMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdsCWN5MTjrJ6OO3MEv9AALMTpNDltNAk',
    appId: '1:261400152264:ios:1faf74db5d256804e5fdfd',
    messagingSenderId: '261400152264',
    projectId: 'sistem-monitoring-mobil',
    storageBucket: 'sistem-monitoring-mobil.firebasestorage.app',
    iosBundleId: 'com.example.sistemMonitoringMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfNY7AXiZ0SJwi7aRYS8Jxg6lNb9ToAMU',
    appId: '1:261400152264:web:432944445b6481a5e5fdfd',
    messagingSenderId: '261400152264',
    projectId: 'sistem-monitoring-mobil',
    authDomain: 'sistem-monitoring-mobil.firebaseapp.com',
    storageBucket: 'sistem-monitoring-mobil.firebasestorage.app',
  );

}